# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.40
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

package marisa;
use base qw(Exporter);
use base qw(DynaLoader);
package marisac;
bootstrap marisa;
package marisa;
@EXPORT = qw();

# ---------- BASE METHODS -------------

package marisa;

sub TIEHASH {
    my ($classname,$obj) = @_;
    return bless $obj, $classname;
}

sub CLEAR { }

sub FIRSTKEY { }

sub NEXTKEY { }

sub FETCH {
    my ($self,$field) = @_;
    my $member_func = "swig_${field}_get";
    $self->$member_func();
}

sub STORE {
    my ($self,$field,$newval) = @_;
    my $member_func = "swig_${field}_set";
    $self->$member_func($newval);
}

sub this {
    my $ptr = shift;
    return tied(%$ptr);
}


# ------- FUNCTION WRAPPERS --------

package marisa;


############# Class : marisa::Key ##############

package marisa::Key;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( marisa );
%OWNER = ();
%ITERATORS = ();
*str = *marisac::Key_str;
*length = *marisac::Key_length;
*id = *marisac::Key_id;
*weight = *marisac::Key_weight;
sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        marisac::delete_Key($self);
        delete $OWNER{$self};
    }
}

sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


############# Class : marisa::Query ##############

package marisa::Query;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( marisa );
%OWNER = ();
%ITERATORS = ();
*str = *marisac::Query_str;
*length = *marisac::Query_length;
*key_id = *marisac::Query_key_id;
sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        marisac::delete_Query($self);
        delete $OWNER{$self};
    }
}

sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


############# Class : marisa::Keyset ##############

package marisa::Keyset;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( marisa );
%OWNER = ();
%ITERATORS = ();
sub new {
    my $pkg = shift;
    my $self = marisac::new_Keyset(@_);
    bless $self, $pkg if defined($self);
}

sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        marisac::delete_Keyset($self);
        delete $OWNER{$self};
    }
}

*push_back = *marisac::Keyset_push_back;
*key = *marisac::Keyset_key;
*num_keys = *marisac::Keyset_num_keys;
*empty = *marisac::Keyset_empty;
*size = *marisac::Keyset_size;
*total_length = *marisac::Keyset_total_length;
*reset = *marisac::Keyset_reset;
*clear = *marisac::Keyset_clear;
sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


############# Class : marisa::Agent ##############

package marisa::Agent;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( marisa );
%OWNER = ();
%ITERATORS = ();
sub new {
    my $pkg = shift;
    my $self = marisac::new_Agent(@_);
    bless $self, $pkg if defined($self);
}

sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        marisac::delete_Agent($self);
        delete $OWNER{$self};
    }
}

*set_query = *marisac::Agent_set_query;
*key = *marisac::Agent_key;
*query = *marisac::Agent_query;
sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


############# Class : marisa::Trie ##############

package marisa::Trie;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( marisa );
%OWNER = ();
%ITERATORS = ();
sub new {
    my $pkg = shift;
    my $self = marisac::new_Trie(@_);
    bless $self, $pkg if defined($self);
}

sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        marisac::delete_Trie($self);
        delete $OWNER{$self};
    }
}

*build = *marisac::Trie_build;
*mmap = *marisac::Trie_mmap;
*load = *marisac::Trie_load;
*save = *marisac::Trie_save;
*lookup = *marisac::Trie_lookup;
*reverse_lookup = *marisac::Trie_reverse_lookup;
*common_prefix_search = *marisac::Trie_common_prefix_search;
*predictive_search = *marisac::Trie_predictive_search;
*num_tries = *marisac::Trie_num_tries;
*num_keys = *marisac::Trie_num_keys;
*num_nodes = *marisac::Trie_num_nodes;
*tail_mode = *marisac::Trie_tail_mode;
*node_order = *marisac::Trie_node_order;
*empty = *marisac::Trie_empty;
*size = *marisac::Trie_size;
*total_size = *marisac::Trie_total_size;
*io_size = *marisac::Trie_io_size;
*clear = *marisac::Trie_clear;
sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


# ------- VARIABLE STUBS --------

package marisa;

*MARISA_OK = *marisac::MARISA_OK;
*MARISA_STATE_ERROR = *marisac::MARISA_STATE_ERROR;
*MARISA_NULL_ERROR = *marisac::MARISA_NULL_ERROR;
*MARISA_BOUND_ERROR = *marisac::MARISA_BOUND_ERROR;
*MARISA_RANGE_ERROR = *marisac::MARISA_RANGE_ERROR;
*MARISA_CODE_ERROR = *marisac::MARISA_CODE_ERROR;
*MARISA_RESET_ERROR = *marisac::MARISA_RESET_ERROR;
*MARISA_SIZE_ERROR = *marisac::MARISA_SIZE_ERROR;
*MARISA_MEMORY_ERROR = *marisac::MARISA_MEMORY_ERROR;
*MARISA_IO_ERROR = *marisac::MARISA_IO_ERROR;
*MARISA_FORMAT_ERROR = *marisac::MARISA_FORMAT_ERROR;
*MARISA_MIN_NUM_TRIES = *marisac::MARISA_MIN_NUM_TRIES;
*MARISA_MAX_NUM_TRIES = *marisac::MARISA_MAX_NUM_TRIES;
*MARISA_DEFAULT_NUM_TRIES = *marisac::MARISA_DEFAULT_NUM_TRIES;
*MARISA_HUGE_CACHE = *marisac::MARISA_HUGE_CACHE;
*MARISA_LARGE_CACHE = *marisac::MARISA_LARGE_CACHE;
*MARISA_NORMAL_CACHE = *marisac::MARISA_NORMAL_CACHE;
*MARISA_SMALL_CACHE = *marisac::MARISA_SMALL_CACHE;
*MARISA_TINY_CACHE = *marisac::MARISA_TINY_CACHE;
*MARISA_DEFAULT_CACHE = *marisac::MARISA_DEFAULT_CACHE;
*MARISA_TEXT_TAIL = *marisac::MARISA_TEXT_TAIL;
*MARISA_BINARY_TAIL = *marisac::MARISA_BINARY_TAIL;
*MARISA_DEFAULT_TAIL = *marisac::MARISA_DEFAULT_TAIL;
*MARISA_LABEL_ORDER = *marisac::MARISA_LABEL_ORDER;
*MARISA_WEIGHT_ORDER = *marisac::MARISA_WEIGHT_ORDER;
*MARISA_DEFAULT_ORDER = *marisac::MARISA_DEFAULT_ORDER;
1;
